env:
  commonjs: true
  es2021: true
  node: true
extends:
  - standard
ignorePatterns: 
  - "**/__tests__/**" 
  - "**/?(*.)+(spec|test).[tj]s?(x)"
parserOptions:
  ecmaVersion: latest
rules: 
  quotes: 
    - 2
    - single
    - avoidEscape: true
      allowTemplateLiterals: true
  semi: 
    - 2 
    - always
  space-before-function-paren: 
    - 2
    - anonymous: always
      named: never
      asyncArrow: always
  space-in-parens: 0
  space-unary-ops: 0
